version = 1

exclude_patterns = [
  "generated/*",
  "*_pb2.py",
  "*_pb2_grpc.py"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]